apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rg10m6ntg-dotnet-basic
  janus-idp.io/tekton: rg10m6ntg-dotnet-basic
  backstage.io/kubernetes-id: rg10m6ntg-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rg10m6ntg-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
